spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource ##指定使用的数据池类  
    druid:
      testDb:
        url: jdbc:mysql://localhost:3306/testDb?createDatabaseIfNotExist=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1 #初始化连接数
        minIdle: 1 #最小连接数
        maxActive: 50 #最大连接数
        maxWait: 60000 #获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall,log4j2 # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
#          auto: none
#           auto: create
           auto: update

---           
logging:
  config: classpath:log4j2.xml
  
